import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# =========================================================
# SMTP CONFIGURATION
# =========================================================
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587

SENDER_EMAIL = "sreya00713@gmail.com"
APP_PASSWORD = "okbhdyhfjsehtthc"
RECIPIENT = "gautam@hawkinscookers.com"


def send_admin_login_alert(username, ip_address):
    message = MIMEMultipart()
    message["From"] = SENDER_EMAIL
    message["To"] = RECIPIENT
    message["Subject"] = "Hawkins Security Alert - Administrator Login"

    body = f"""
HAWKINS COOKERS LIMITED

Cybersecurity Awareness Platform
Administrator Login Detected

----------------------------------------
Username      : {username}
Login Time    : {datetime.now().strftime('%d-%b-%Y %I:%M:%S %p')}
IP Address    : {ip_address}
Status        : SUCCESS
----------------------------------------

If you have not initiated this login, kindly reply back to this email, subjected to Unauthorized Admin Portal Access.

This notification has been automatically generated by the Hawkins Cybersecurity Awareness Platform.
"""

    message.attach(MIMEText(body, "plain"))

    try:
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(SENDER_EMAIL, APP_PASSWORD)
        server.sendmail(SENDER_EMAIL, RECIPIENT, message.as_string())
        server.quit()
    except Exception as e:
        print(f"Failed to send admin login alert: {e}")


def send_bruteforce_alert(username, ip_address, failed_attempts):
    message = MIMEMultipart()
    message["From"] = SENDER_EMAIL
    message["To"] = RECIPIENT
    message["Subject"] = "🚨 Hawkins Security Alert - Brute Force Attack Detected"

    body = f"""
HAWKINS COOKERS LIMITED

Cybersecurity Awareness Platform
CRITICAL SECURITY ALERT

----------------------------------------
Possible Brute Force Attack Detected

Username           : {username}
Failed Attempts    : {failed_attempts}
Source IP Address  : {ip_address}
Detection Time     : {datetime.now().strftime('%d-%b-%Y %I:%M:%S %p')}
Status             : ACCOUNT LOCKED

Lock Duration      : 15 Minutes
----------------------------------------

The administrator account has been temporarily locked after multiple consecutive failed login attempts.

If this activity was NOT initiated by you, please investigate immediately.

This notification has been automatically generated by the Hawkins Cybersecurity Awareness Platform.
"""

    message.attach(MIMEText(body, "plain"))

    try:
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(SENDER_EMAIL, APP_PASSWORD)
        server.sendmail(SENDER_EMAIL, RECIPIENT, message.as_string())
        server.quit()
    except Exception as e:
        print(f"Failed to send brute-force alert: {e}")